//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpSlam.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharpSlam.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remoteApi.dll missing.
        /// </summary>
        internal static string ErrorMessage_DLL {
            get {
                return ResourceManager.GetString("ErrorMessage_DLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 127.0.0.1.
        /// </summary>
        internal static string Localhost {
            get {
                return ResourceManager.GetString("Localhost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to measuredDataAtThisTime0.
        /// </summary>
        internal static string MeasuredData0 {
            get {
                return ResourceManager.GetString("MeasuredData0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neobotix#0.
        /// </summary>
        internal static string Neobotix {
            get {
                return ResourceManager.GetString("Neobotix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to origo.
        /// </summary>
        internal static string Origo {
            get {
                return ResourceManager.GetString("Origo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        internal static string Reconnect {
            get {
                return ResourceManager.GetString("Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SICK_S300_fast#0.
        /// </summary>
        internal static string SICKS300 {
            get {
                return ResourceManager.GetString("SICKS300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start simulation.
        /// </summary>
        internal static string StartSimulation {
            get {
                return ResourceManager.GetString("StartSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop simulation.
        /// </summary>
        internal static string StopSimulation {
            get {
                return ResourceManager.GetString("StopSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 192.168.1.233.
        /// </summary>
        internal static string TestRobotIP_001 {
            get {
                return ResourceManager.GetString("TestRobotIP_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wheel_left#0.
        /// </summary>
        internal static string WheelLeft0 {
            get {
                return ResourceManager.GetString("WheelLeft0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wheel_right#0.
        /// </summary>
        internal static string WheelRight0 {
            get {
                return ResourceManager.GetString("WheelRight0", resourceCulture);
            }
        }
    }
}
